package com.android.billingclient.api;

import kotlin.coroutines.jvm.internal.DEXi.JuorMn;

/* JADX INFO: loaded from: classes2.dex */
public abstract class zzce {
    public static final BillingResult zzA;
    public static final BillingResult zzB;
    public static final BillingResult zzC;
    public static final BillingResult zzD;
    public static final BillingResult zzE;
    public static final BillingResult zzF;
    public static final BillingResult zza;
    public static final BillingResult zzb;
    public static final BillingResult zzc;
    public static final BillingResult zzd;
    public static final BillingResult zzf;
    public static final BillingResult zzg;
    public static final BillingResult zzh;
    public static final BillingResult zzi;
    public static final BillingResult zzj;
    public static final BillingResult zzl;
    public static final BillingResult zzm;
    public static final BillingResult zzn;
    public static final BillingResult zzo;
    public static final BillingResult zzp;
    public static final BillingResult zzr;
    public static final BillingResult zzs;
    public static final BillingResult zzt;
    public static final BillingResult zzu;
    public static final BillingResult zzv;
    public static final BillingResult zzw;
    public static final BillingResult zzy;
    public static final BillingResult zzz;

    public static BillingResult zza(int i, String str) {
        BillingResult.Builder builderNewBuilder = BillingResult.newBuilder();
        builderNewBuilder.zza = i;
        builderNewBuilder.zzb = str;
        return builderNewBuilder.build();
    }

    static {
        BillingResult.Builder builderNewBuilder = BillingResult.newBuilder();
        builderNewBuilder.zza = 3;
        builderNewBuilder.zzb = "Google Play In-app Billing API version is less than 3";
        zza = builderNewBuilder.build();
        BillingResult.Builder builderNewBuilder2 = BillingResult.newBuilder();
        builderNewBuilder2.zza = 3;
        builderNewBuilder2.zzb = "Google Play In-app Billing API version is less than 9";
        zzb = builderNewBuilder2.build();
        BillingResult.Builder builderNewBuilder3 = BillingResult.newBuilder();
        builderNewBuilder3.zza = 3;
        builderNewBuilder3.zzb = "Billing service unavailable on device.";
        zzc = builderNewBuilder3.build();
        BillingResult.Builder builderNewBuilder4 = BillingResult.newBuilder();
        builderNewBuilder4.zza = 5;
        builderNewBuilder4.zzb = "Client is already in the process of connecting to billing service.";
        zzd = builderNewBuilder4.build();
        BillingResult.Builder builderNewBuilder5 = BillingResult.newBuilder();
        builderNewBuilder5.zza = 5;
        builderNewBuilder5.zzb = "The list of SKUs can't be empty.";
        builderNewBuilder5.build();
        BillingResult.Builder builderNewBuilder6 = BillingResult.newBuilder();
        builderNewBuilder6.zza = 5;
        builderNewBuilder6.zzb = JuorMn.cHFEY;
        zzf = builderNewBuilder6.build();
        BillingResult.Builder builderNewBuilder7 = BillingResult.newBuilder();
        builderNewBuilder7.zza = 5;
        builderNewBuilder7.zzb = "Product type can't be empty.";
        zzg = builderNewBuilder7.build();
        BillingResult.Builder builderNewBuilder8 = BillingResult.newBuilder();
        builderNewBuilder8.zza = -2;
        builderNewBuilder8.zzb = "Client does not support extra params.";
        zzh = builderNewBuilder8.build();
        BillingResult.Builder builderNewBuilder9 = BillingResult.newBuilder();
        builderNewBuilder9.zza = 5;
        builderNewBuilder9.zzb = "Invalid purchase token.";
        zzi = builderNewBuilder9.build();
        BillingResult.Builder builderNewBuilder10 = BillingResult.newBuilder();
        builderNewBuilder10.zza = 6;
        builderNewBuilder10.zzb = "An internal error occurred.";
        zzj = builderNewBuilder10.build();
        BillingResult.Builder builderNewBuilder11 = BillingResult.newBuilder();
        builderNewBuilder11.zza = 5;
        builderNewBuilder11.zzb = "SKU can't be null.";
        builderNewBuilder11.build();
        BillingResult.Builder builderNewBuilder12 = BillingResult.newBuilder();
        builderNewBuilder12.zza = 0;
        zzl = builderNewBuilder12.build();
        BillingResult.Builder builderNewBuilder13 = BillingResult.newBuilder();
        builderNewBuilder13.zza = -1;
        builderNewBuilder13.zzb = "Service connection is disconnected.";
        zzm = builderNewBuilder13.build();
        BillingResult.Builder builderNewBuilder14 = BillingResult.newBuilder();
        builderNewBuilder14.zza = 2;
        builderNewBuilder14.zzb = "Timeout communicating with service.";
        zzn = builderNewBuilder14.build();
        BillingResult.Builder builderNewBuilder15 = BillingResult.newBuilder();
        builderNewBuilder15.zza = -2;
        builderNewBuilder15.zzb = "Client does not support subscriptions.";
        zzo = builderNewBuilder15.build();
        BillingResult.Builder builderNewBuilder16 = BillingResult.newBuilder();
        builderNewBuilder16.zza = -2;
        builderNewBuilder16.zzb = "Client does not support subscriptions update.";
        zzp = builderNewBuilder16.build();
        BillingResult.Builder builderNewBuilder17 = BillingResult.newBuilder();
        builderNewBuilder17.zza = -2;
        builderNewBuilder17.zzb = "Client does not support get purchase history.";
        builderNewBuilder17.build();
        BillingResult.Builder builderNewBuilder18 = BillingResult.newBuilder();
        builderNewBuilder18.zza = -2;
        builderNewBuilder18.zzb = "Client does not support price change confirmation.";
        zzr = builderNewBuilder18.build();
        BillingResult.Builder builderNewBuilder19 = BillingResult.newBuilder();
        builderNewBuilder19.zza = -2;
        builderNewBuilder19.zzb = "Play Store version installed does not support cross selling products.";
        zzs = builderNewBuilder19.build();
        BillingResult.Builder builderNewBuilder20 = BillingResult.newBuilder();
        builderNewBuilder20.zza = -2;
        builderNewBuilder20.zzb = "Client does not support multi-item purchases.";
        zzt = builderNewBuilder20.build();
        BillingResult.Builder builderNewBuilder21 = BillingResult.newBuilder();
        builderNewBuilder21.zza = -2;
        builderNewBuilder21.zzb = "Client does not support offer_id_token.";
        zzu = builderNewBuilder21.build();
        BillingResult.Builder builderNewBuilder22 = BillingResult.newBuilder();
        builderNewBuilder22.zza = -2;
        builderNewBuilder22.zzb = "Client does not support ProductDetails.";
        zzv = builderNewBuilder22.build();
        BillingResult.Builder builderNewBuilder23 = BillingResult.newBuilder();
        builderNewBuilder23.zza = -2;
        builderNewBuilder23.zzb = "Client does not support in-app messages.";
        zzw = builderNewBuilder23.build();
        BillingResult.Builder builderNewBuilder24 = BillingResult.newBuilder();
        builderNewBuilder24.zza = -2;
        builderNewBuilder24.zzb = "Client does not support user choice billing.";
        builderNewBuilder24.build();
        BillingResult.Builder builderNewBuilder25 = BillingResult.newBuilder();
        builderNewBuilder25.zza = -2;
        builderNewBuilder25.zzb = "Play Store version installed does not support external offer.";
        zzy = builderNewBuilder25.build();
        BillingResult.Builder builderNewBuilder26 = BillingResult.newBuilder();
        builderNewBuilder26.zza = 5;
        builderNewBuilder26.zzb = "Unknown feature";
        zzz = builderNewBuilder26.build();
        BillingResult.Builder builderNewBuilder27 = BillingResult.newBuilder();
        builderNewBuilder27.zza = -2;
        builderNewBuilder27.zzb = "Play Store version installed does not support get billing config.";
        zzA = builderNewBuilder27.build();
        BillingResult.Builder builderNewBuilder28 = BillingResult.newBuilder();
        builderNewBuilder28.zza = -2;
        builderNewBuilder28.zzb = "Query product details with serialized docid is not supported.";
        zzB = builderNewBuilder28.build();
        BillingResult.Builder builderNewBuilder29 = BillingResult.newBuilder();
        builderNewBuilder29.zza = 4;
        builderNewBuilder29.zzb = "Item is unavailable for purchase.";
        zzC = builderNewBuilder29.build();
        BillingResult.Builder builderNewBuilder30 = BillingResult.newBuilder();
        builderNewBuilder30.zza = -2;
        builderNewBuilder30.zzb = "Query product details with developer specified account is not supported.";
        zzD = builderNewBuilder30.build();
        BillingResult.Builder builderNewBuilder31 = BillingResult.newBuilder();
        builderNewBuilder31.zza = -2;
        builderNewBuilder31.zzb = "Play Store version installed does not support alternative billing only.";
        zzE = builderNewBuilder31.build();
        BillingResult.Builder builderNewBuilder32 = BillingResult.newBuilder();
        builderNewBuilder32.zza = 5;
        builderNewBuilder32.zzb = "To use this API you must specify a PurchasesUpdateListener when initializing a BillingClient.";
        zzF = builderNewBuilder32.build();
    }
}
