package com.google.android.gms.games.internal.player;

import android.os.Parcel;
import android.os.Parcelable;
import androidx.core.internal.view.Oteb.nYVxXTZQ;
import com.google.firebase.auth.zzz;
import java.util.Arrays;
import kotlin.io.CloseableKt;

/* JADX INFO: loaded from: classes2.dex */
public final class zze extends com.google.android.gms.games.internal.zzg {
    public static final Parcelable.Creator<zze> CREATOR = new zzf();
    public final boolean zza;
    public final boolean zzb;
    public final boolean zzc;
    public final boolean zzd;
    public final boolean zze;
    public final boolean zzf;
    public final boolean zzg;
    public final boolean zzh;
    public final boolean zzi;
    public final boolean zzj;

    public zze(boolean z, boolean z2, boolean z3, boolean z4, boolean z5, boolean z6, boolean z7, boolean z8, boolean z9, boolean z10) {
        this.zza = z;
        this.zzb = z2;
        this.zzc = z3;
        this.zzd = z4;
        this.zze = z5;
        this.zzf = z6;
        this.zzg = z7;
        this.zzh = z8;
        this.zzi = z9;
        this.zzj = z10;
    }

    public final boolean equals(Object obj) {
        if (!(obj instanceof zze)) {
            return false;
        }
        if (this == obj) {
            return true;
        }
        zze zzeVar = (zze) obj;
        return this.zza == zzeVar.zza && this.zzb == zzeVar.zzb && this.zzc == zzeVar.zzc && this.zzd == zzeVar.zzd && this.zze == zzeVar.zze && this.zzf == zzeVar.zzf && this.zzg == zzeVar.zzg && this.zzh == zzeVar.zzh && this.zzi == zzeVar.zzi && this.zzj == zzeVar.zzj;
    }

    public final int hashCode() {
        return Arrays.hashCode(new Object[]{Boolean.valueOf(this.zza), Boolean.valueOf(this.zzb), Boolean.valueOf(this.zzc), Boolean.valueOf(this.zzd), Boolean.valueOf(this.zze), Boolean.valueOf(this.zzf), Boolean.valueOf(this.zzg), Boolean.valueOf(this.zzh), Boolean.valueOf(this.zzi), Boolean.valueOf(this.zzj)});
    }

    @Override // android.os.Parcelable
    public final void writeToParcel(Parcel parcel, int i) {
        int iZza = CloseableKt.zza(parcel, 20293);
        CloseableKt.zzc(parcel, 1, 4);
        parcel.writeInt(this.zza ? 1 : 0);
        CloseableKt.zzc(parcel, 2, 4);
        parcel.writeInt(this.zzb ? 1 : 0);
        CloseableKt.zzc(parcel, 3, 4);
        parcel.writeInt(this.zzc ? 1 : 0);
        CloseableKt.zzc(parcel, 4, 4);
        parcel.writeInt(this.zzd ? 1 : 0);
        CloseableKt.zzc(parcel, 5, 4);
        parcel.writeInt(this.zze ? 1 : 0);
        CloseableKt.zzc(parcel, 6, 4);
        parcel.writeInt(this.zzf ? 1 : 0);
        CloseableKt.zzc(parcel, 7, 4);
        parcel.writeInt(this.zzg ? 1 : 0);
        CloseableKt.zzc(parcel, 8, 4);
        parcel.writeInt(this.zzh ? 1 : 0);
        CloseableKt.zzc(parcel, 9, 4);
        parcel.writeInt(this.zzi ? 1 : 0);
        CloseableKt.zzc(parcel, 10, 4);
        parcel.writeInt(this.zzj ? 1 : 0);
        CloseableKt.zzb(parcel, iZza);
    }

    public final String toString() {
        zzz zzzVar = new zzz(this);
        zzzVar.add(Boolean.valueOf(this.zza), "forbiddenToHavePlayerProfile");
        zzzVar.add(Boolean.valueOf(this.zzb), "requiresParentPermissionToShareData");
        zzzVar.add(Boolean.valueOf(this.zzc), "hasSettingsControlledByParent");
        zzzVar.add(Boolean.valueOf(this.zzd), "requiresParentPermissionToUsePlayTogether");
        zzzVar.add(Boolean.valueOf(this.zze), "canUseOnlyAutoGeneratedGamerTag");
        zzzVar.add(Boolean.valueOf(this.zzf), "forbiddenToRecordVideo");
        zzzVar.add(Boolean.valueOf(this.zzg), "shouldSeeEquallyWeightedButtonsInConsents");
        zzzVar.add(Boolean.valueOf(this.zzh), nYVxXTZQ.eoBvfFYzVdLSzq);
        zzzVar.add(Boolean.valueOf(this.zzi), "shouldSeeSimplifiedConsentMessages");
        zzzVar.add(Boolean.valueOf(this.zzj), "forbiddenToUseProfilelessRecall");
        return zzzVar.toString();
    }
}
