package com.google.android.gms.internal.ads;

import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import com.google.android.gms.ads.internal.util.client.VersionInfoParcel;
import com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import kotlin.io.CloseableKt;

/* JADX INFO: loaded from: classes.dex */
public final class zzbuw extends AbstractSafeParcelable {
    public static final Parcelable.Creator<zzbuw> CREATOR = new zzbux();
    public final long zzA;
    public final String zzB;
    public final float zzC;
    public final int zzD;
    public final int zzE;
    public final boolean zzF;
    public final String zzG;
    public final boolean zzH;
    public final String zzI;
    public final boolean zzJ;
    public final int zzK;
    public final Bundle zzL;
    public final String zzM;
    public final com.google.android.gms.ads.internal.client.zzeh zzN;
    public final boolean zzO;
    public final Bundle zzP;
    public final String zzQ;
    public final String zzR;
    public final String zzS;
    public final boolean zzT;
    public final List zzU;
    public final String zzV;
    public final List zzW;
    public final int zzX;
    public final boolean zzY;
    public final boolean zzZ;
    public final int zza;
    public final boolean zzaa;
    public final ArrayList zzab;
    public final String zzac;
    public final zzbmp zzad;
    public final String zzae;
    public final Bundle zzaf;
    public final Bundle zzb;
    public final com.google.android.gms.ads.internal.client.zzm zzc;
    public final com.google.android.gms.ads.internal.client.zzr zzd;
    public final String zze;
    public final ApplicationInfo zzf;
    public final PackageInfo zzg;
    public final String zzh;
    public final String zzi;
    public final String zzj;
    public final VersionInfoParcel zzk;
    public final Bundle zzl;
    public final int zzm;
    public final List zzn;
    public final Bundle zzo;
    public final boolean zzp;
    public final int zzq;
    public final int zzr;
    public final float zzs;
    public final String zzt;
    public final long zzu;
    public final String zzv;
    public final List zzw;
    public final String zzx;
    public final zzbge zzy;
    public final List zzz;

    public zzbuw(int i, Bundle bundle, com.google.android.gms.ads.internal.client.zzm zzmVar, com.google.android.gms.ads.internal.client.zzr zzrVar, String str, ApplicationInfo applicationInfo, PackageInfo packageInfo, String str2, String str3, String str4, VersionInfoParcel versionInfoParcel, Bundle bundle2, int i2, List list, Bundle bundle3, boolean z, int i3, int i4, float f, String str5, long j, String str6, List list2, String str7, zzbge zzbgeVar, List list3, long j2, String str8, float f2, boolean z2, int i5, int i6, boolean z3, String str9, String str10, boolean z4, int i7, Bundle bundle4, String str11, com.google.android.gms.ads.internal.client.zzeh zzehVar, boolean z5, Bundle bundle5, String str12, String str13, String str14, boolean z6, List list4, String str15, List list5, int i8, boolean z7, boolean z8, boolean z9, ArrayList arrayList, String str16, zzbmp zzbmpVar, String str17, Bundle bundle6) {
        this.zza = i;
        this.zzb = bundle;
        this.zzc = zzmVar;
        this.zzd = zzrVar;
        this.zze = str;
        this.zzf = applicationInfo;
        this.zzg = packageInfo;
        this.zzh = str2;
        this.zzi = str3;
        this.zzj = str4;
        this.zzk = versionInfoParcel;
        this.zzl = bundle2;
        this.zzm = i2;
        this.zzn = list;
        this.zzz = list3 == null ? Collections.emptyList() : Collections.unmodifiableList(list3);
        this.zzo = bundle3;
        this.zzp = z;
        this.zzq = i3;
        this.zzr = i4;
        this.zzs = f;
        this.zzt = str5;
        this.zzu = j;
        this.zzv = str6;
        this.zzw = list2 == null ? Collections.emptyList() : Collections.unmodifiableList(list2);
        this.zzx = str7;
        this.zzy = zzbgeVar;
        this.zzA = j2;
        this.zzB = str8;
        this.zzC = f2;
        this.zzH = z2;
        this.zzD = i5;
        this.zzE = i6;
        this.zzF = z3;
        this.zzG = str9;
        this.zzI = str10;
        this.zzJ = z4;
        this.zzK = i7;
        this.zzL = bundle4;
        this.zzM = str11;
        this.zzN = zzehVar;
        this.zzO = z5;
        this.zzP = bundle5;
        this.zzQ = str12;
        this.zzR = str13;
        this.zzS = str14;
        this.zzT = z6;
        this.zzU = list4;
        this.zzV = str15;
        this.zzW = list5;
        this.zzX = i8;
        this.zzY = z7;
        this.zzZ = z8;
        this.zzaa = z9;
        this.zzab = arrayList;
        this.zzac = str16;
        this.zzad = zzbmpVar;
        this.zzae = str17;
        this.zzaf = bundle6;
    }

    @Override // android.os.Parcelable
    public final void writeToParcel(Parcel parcel, int i) {
        int i2 = this.zza;
        int iZza = CloseableKt.zza(parcel, 20293);
        CloseableKt.zzc(parcel, 1, 4);
        parcel.writeInt(i2);
        CloseableKt.writeBundle(parcel, 2, this.zzb, false);
        CloseableKt.writeParcelable(parcel, 3, this.zzc, i, false);
        CloseableKt.writeParcelable(parcel, 4, this.zzd, i, false);
        CloseableKt.writeString(parcel, 5, this.zze, false);
        CloseableKt.writeParcelable(parcel, 6, this.zzf, i, false);
        CloseableKt.writeParcelable(parcel, 7, this.zzg, i, false);
        CloseableKt.writeString(parcel, 8, this.zzh, false);
        CloseableKt.writeString(parcel, 9, this.zzi, false);
        CloseableKt.writeString(parcel, 10, this.zzj, false);
        CloseableKt.writeParcelable(parcel, 11, this.zzk, i, false);
        CloseableKt.writeBundle(parcel, 12, this.zzl, false);
        int i3 = this.zzm;
        CloseableKt.zzc(parcel, 13, 4);
        parcel.writeInt(i3);
        CloseableKt.writeStringList(parcel, 14, this.zzn);
        CloseableKt.writeBundle(parcel, 15, this.zzo, false);
        boolean z = this.zzp;
        CloseableKt.zzc(parcel, 16, 4);
        parcel.writeInt(z ? 1 : 0);
        int i4 = this.zzq;
        CloseableKt.zzc(parcel, 18, 4);
        parcel.writeInt(i4);
        int i5 = this.zzr;
        CloseableKt.zzc(parcel, 19, 4);
        parcel.writeInt(i5);
        float f = this.zzs;
        CloseableKt.zzc(parcel, 20, 4);
        parcel.writeFloat(f);
        CloseableKt.writeString(parcel, 21, this.zzt, false);
        long j = this.zzu;
        CloseableKt.zzc(parcel, 25, 8);
        parcel.writeLong(j);
        CloseableKt.writeString(parcel, 26, this.zzv, false);
        CloseableKt.writeStringList(parcel, 27, this.zzw);
        CloseableKt.writeString(parcel, 28, this.zzx, false);
        CloseableKt.writeParcelable(parcel, 29, this.zzy, i, false);
        CloseableKt.writeStringList(parcel, 30, this.zzz);
        long j2 = this.zzA;
        CloseableKt.zzc(parcel, 31, 8);
        parcel.writeLong(j2);
        CloseableKt.writeString(parcel, 33, this.zzB, false);
        float f2 = this.zzC;
        CloseableKt.zzc(parcel, 34, 4);
        parcel.writeFloat(f2);
        int i6 = this.zzD;
        CloseableKt.zzc(parcel, 35, 4);
        parcel.writeInt(i6);
        int i7 = this.zzE;
        CloseableKt.zzc(parcel, 36, 4);
        parcel.writeInt(i7);
        boolean z2 = this.zzF;
        CloseableKt.zzc(parcel, 37, 4);
        parcel.writeInt(z2 ? 1 : 0);
        CloseableKt.writeString(parcel, 39, this.zzG, false);
        boolean z3 = this.zzH;
        CloseableKt.zzc(parcel, 40, 4);
        parcel.writeInt(z3 ? 1 : 0);
        CloseableKt.writeString(parcel, 41, this.zzI, false);
        boolean z4 = this.zzJ;
        CloseableKt.zzc(parcel, 42, 4);
        parcel.writeInt(z4 ? 1 : 0);
        int i8 = this.zzK;
        CloseableKt.zzc(parcel, 43, 4);
        parcel.writeInt(i8);
        CloseableKt.writeBundle(parcel, 44, this.zzL, false);
        CloseableKt.writeString(parcel, 45, this.zzM, false);
        CloseableKt.writeParcelable(parcel, 46, this.zzN, i, false);
        boolean z5 = this.zzO;
        CloseableKt.zzc(parcel, 47, 4);
        parcel.writeInt(z5 ? 1 : 0);
        CloseableKt.writeBundle(parcel, 48, this.zzP, false);
        CloseableKt.writeString(parcel, 49, this.zzQ, false);
        CloseableKt.writeString(parcel, 50, this.zzR, false);
        CloseableKt.writeString(parcel, 51, this.zzS, false);
        boolean z6 = this.zzT;
        CloseableKt.zzc(parcel, 52, 4);
        parcel.writeInt(z6 ? 1 : 0);
        List list = this.zzU;
        if (list != null) {
            int iZza2 = CloseableKt.zza(parcel, 53);
            int size = list.size();
            parcel.writeInt(size);
            for (int i9 = 0; i9 < size; i9++) {
                parcel.writeInt(((Integer) list.get(i9)).intValue());
            }
            CloseableKt.zzb(parcel, iZza2);
        }
        CloseableKt.writeString(parcel, 54, this.zzV, false);
        CloseableKt.writeStringList(parcel, 55, this.zzW);
        int i10 = this.zzX;
        CloseableKt.zzc(parcel, 56, 4);
        parcel.writeInt(i10);
        boolean z7 = this.zzY;
        CloseableKt.zzc(parcel, 57, 4);
        parcel.writeInt(z7 ? 1 : 0);
        boolean z8 = this.zzZ;
        CloseableKt.zzc(parcel, 58, 4);
        parcel.writeInt(z8 ? 1 : 0);
        boolean z9 = this.zzaa;
        CloseableKt.zzc(parcel, 59, 4);
        parcel.writeInt(z9 ? 1 : 0);
        CloseableKt.writeStringList(parcel, 60, this.zzab);
        CloseableKt.writeString(parcel, 61, this.zzac, false);
        CloseableKt.writeParcelable(parcel, 63, this.zzad, i, false);
        CloseableKt.writeString(parcel, 64, this.zzae, false);
        CloseableKt.writeBundle(parcel, 65, this.zzaf, false);
        CloseableKt.zzb(parcel, iZza);
    }
}
