package com.google.android.gms.measurement.internal;

import android.content.Context;
import com.google.android.gms.auth.api.LNi.xPQrbOSWiEdU;
import com.google.android.gms.games.event.AfJ.oKjScaD;
import com.google.android.gms.internal.measurement.zzhf;
import com.google.android.gms.internal.measurement.zzhq;
import com.google.firebase.analytics.connector.pDv.PZmDzEagKNdW;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Map;

/* JADX INFO: loaded from: classes2.dex */
public abstract class zzdu {
    public static final zzdt zzA;
    public static final zzdt zzB;
    public static final zzdt zzC;
    public static final zzdt zzD;
    public static final zzdt zzE;
    public static final zzdt zzF;
    public static final zzdt zzG;
    public static final zzdt zzH;
    public static final zzdt zzI;
    public static final zzdt zzJ;
    public static final zzdt zzK;
    public static final zzdt zzL;
    public static final zzdt zzM;
    public static final zzdt zzN;
    public static final zzdt zzO;
    public static final zzdt zzP;
    public static final zzdt zzQ;
    public static final zzdt zzR;
    public static final zzdt zzT;
    public static final zzdt zzU;
    public static final zzdt zzV;
    public static final zzdt zzW;
    public static final zzdt zzX;
    public static final zzdt zzY;
    public static final zzdt zzZ;
    public static final zzdt zza;
    public static final zzdt zzaa;
    public static final zzdt zzab;
    public static final zzdt zzac;
    public static final zzdt zzad;
    public static final zzdt zzaf;
    public static final zzdt zzai;
    public static final zzdt zzaj;
    public static final zzdt zzal;
    public static final zzdt zzam;
    public static final zzdt zzan;
    public static final zzdt zzao;
    public static final zzdt zzap;
    public static final zzdt zzaq;
    public static final zzdt zzas;
    public static final zzdt zzat;
    public static final zzdt zzau;
    public static final List zzav = Collections.synchronizedList(new ArrayList());
    public static final zzdt zzb;
    public static final zzdt zzc;
    public static final zzdt zzd;
    public static final zzdt zze;
    public static final zzdt zzf;
    public static final zzdt zzg;
    public static final zzdt zzh;
    public static final zzdt zzi;
    public static final zzdt zzj;
    public static final zzdt zzk;
    public static final zzdt zzl;
    public static final zzdt zzm;
    public static final zzdt zzn;
    public static final zzdt zzo;
    public static final zzdt zzp;
    public static final zzdt zzq;
    public static final zzdt zzr;
    public static final zzdt zzs;
    public static final zzdt zzt;
    public static final zzdt zzu;
    public static final zzdt zzv;
    public static final zzdt zzw;
    public static final zzdt zzx;
    public static final zzdt zzy;
    public static final zzdt zzz;

    public static zzdt zza(String str, Object obj, Object obj2, zzdq zzdqVar) {
        zzdt zzdtVar = new zzdt(str, obj, obj2, zzdqVar);
        zzav.add(zzdtVar);
        return zzdtVar;
    }

    static {
        Collections.synchronizedSet(new HashSet());
        zza = zza("measurement.ad_id_cache_time", 10000L, 10000L, zzae.zza$11);
        zzb = zza("measurement.monitoring.sample_period_millis", 86400000L, 86400000L, zzae.zza$3);
        zzc = zza("measurement.config.cache_time", 86400000L, 3600000L, zzae.zza$15);
        zzd = zza("measurement.config.url_scheme", "https", "https", zzae.zza$27);
        zze = zza("measurement.config.url_authority", "app-measurement.com", "app-measurement.com", zzcc.zza$9);
        zzf = zza("measurement.upload.max_bundles", 100, 100, zzcc.zza$21);
        zzg = zza("measurement.upload.max_batch_size", 65536, 65536, zzdg.zza$2);
        zzh = zza("measurement.upload.max_bundle_size", 65536, 65536, zzdg.zza$3);
        zzi = zza("measurement.upload.max_events_per_bundle", 1000, 1000, zzdg.zza$4);
        zzj = zza("measurement.upload.max_events_per_day", 100000, 100000, zzdg.zza$5);
        zzk = zza("measurement.upload.max_error_events_per_day", 1000, 1000, zzae.zza$22);
        zzl = zza("measurement.upload.max_public_events_per_day", 50000, 50000, zzcc.zza$3);
        zzm = zza("measurement.upload.max_conversions_per_day", 10000, 10000, zzcc.zza$14);
        zzn = zza("measurement.upload.max_realtime_events_per_day", 10, 10, zzcc.zza$25);
        zzo = zza("measurement.store.max_stored_events_per_app", 100000, 100000, zzdg.zza$6);
        zzp = zza("measurement.upload.url", "https://app-measurement.com/a", "https://app-measurement.com/a", zzdg.zza$7);
        zzq = zza("measurement.upload.backoff_period", 43200000L, 43200000L, zzdg.zza$8);
        zzr = zza("measurement.upload.window_interval", 3600000L, 3600000L, zzdg.zza$9);
        zzs = zza("measurement.upload.interval", 3600000L, 3600000L, zzae.zza$1);
        zzt = zza("measurement.upload.realtime_upload_interval", 10000L, 10000L, zzae.zza$2);
        zzu = zza("measurement.upload.debug_upload_interval", 1000L, 1000L, zzae.zza$4);
        zzv = zza("measurement.upload.minimum_delay", 500L, 500L, zzae.zza$5);
        zzw = zza("measurement.alarm_manager.minimum_interval", 60000L, 60000L, zzae.zza$6);
        zzx = zza(oKjScaD.sFzdsLNLgmRxYl, 86400000L, 86400000L, zzae.zza$7);
        zzy = zza("measurement.upload.refresh_blacklisted_config_interval", 604800000L, 604800000L, zzae.zza$8);
        zzz = zza("measurement.upload.initial_upload_delay_time", 15000L, 15000L, zzae.zza$9);
        zzA = zza("measurement.upload.retry_time", 1800000L, 1800000L, zzae.zza$10);
        zzB = zza("measurement.upload.retry_count", 6, 6, zzae.zza$12);
        zzC = zza("measurement.upload.max_queue_time", 2419200000L, 2419200000L, zzae.zza$13);
        zzD = zza("measurement.lifetimevalue.max_currency_tracked", 4, 4, zzae.zza$14);
        zzE = zza("measurement.audience.filter_result_max_count", 200, 200, zzae.zza$16);
        zzF = zza("measurement.upload.max_public_user_properties", 25, 25, null);
        zzG = zza("measurement.upload.max_event_name_cardinality", 500, 500, null);
        zzH = zza("measurement.upload.max_public_event_params", 25, 25, null);
        zzI = zza(xPQrbOSWiEdU.juXbzAkGjDq, 5000L, 5000L, zzae.zza$17);
        Boolean bool = Boolean.FALSE;
        zzJ = zza("measurement.test.boolean_flag", bool, bool, zzae.zza$18);
        zzK = zza("measurement.test.string_flag", "---", "---", zzae.zza$19);
        zzL = zza("measurement.test.long_flag", -1L, -1L, zzae.zza$20);
        zzM = zza("measurement.test.int_flag", -2, -2, zzae.zza$21);
        Double dValueOf = Double.valueOf(-3.0d);
        zzN = zza("measurement.test.double_flag", dValueOf, dValueOf, zzae.zza$23);
        zzO = zza("measurement.experiment.max_ids", 50, 50, zzae.zza$24);
        zzP = zza("measurement.max_bundles_per_iteration", 100, 100, zzae.zza$25);
        zzQ = zza("measurement.sdk.attribution.cache.ttl", 604800000L, 604800000L, zzae.zza$26);
        zzR = zza("measurement.redaction.app_instance_id.ttl", 7200000L, 7200000L, zzae.zza$28);
        Boolean bool2 = Boolean.TRUE;
        zza("measurement.collection.log_event_and_bundle_v2", bool2, bool2, zzae.zza$29);
        zzT = zza("measurement.quality.checksum", bool, bool, null);
        zzU = zza("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", bool, bool, zzcc.zza);
        zzV = zza("measurement.audience.refresh_event_count_filters_timestamp", bool, bool, zzcc.zza$1);
        zzW = zza("measurement.audience.use_bundle_timestamp_for_event_count_filters", bool, bool, zzcc.zza$2);
        zzX = zza("measurement.sdk.collection.retrieve_deeplink_from_bow_2", bool2, bool2, zzcc.zza$4);
        zzY = zza("measurement.sdk.collection.last_deep_link_referrer_campaign2", bool, bool, zzcc.zza$5);
        zzZ = zza("measurement.lifecycle.app_in_background_parameter", bool, bool, zzcc.zza$6);
        zzaa = zza("measurement.integration.disable_firebase_instance_id", bool, bool, zzcc.zza$7);
        zzab = zza("measurement.collection.service.update_with_analytics_fix", bool, bool, zzcc.zza$8);
        zzac = zza("measurement.client.firebase_feature_rollout.v1.enable", bool2, bool2, zzcc.zza$10);
        zzad = zza("measurement.client.sessions.check_on_reset_and_enable2", bool2, bool2, zzcc.zza$11);
        zza("measurement.collection.synthetic_data_mitigation", bool, bool, zzcc.zza$12);
        zzaf = zza("measurement.service.storage_consent_support_version", 203600, 203600, zzcc.zza$13);
        zza("measurement.client.click_identifier_control.dev", bool, bool, zzcc.zza$15);
        zza("measurement.service.click_identifier_control", bool, bool, zzcc.zza$16);
        zzai = zza("measurement.service.store_null_safelist", bool2, bool2, zzcc.zza$17);
        zzaj = zza("measurement.service.store_safelist", bool2, bool2, zzcc.zza$18);
        zza("measurement.collection.enable_session_stitching_token.service", bool, bool, zzcc.zza$19);
        zzal = zza("measurement.collection.enable_session_stitching_token.service_new", bool2, bool2, zzcc.zza$20);
        zzam = zza("measurement.collection.enable_session_stitching_token.client.dev", bool2, bool2, zzcc.zza$22);
        zzan = zza("measurement.session_stitching_token_enabled", bool, bool, zzcc.zza$23);
        zzao = zza("measurement.redaction.e_tag", bool2, bool2, zzcc.zza$24);
        zzap = zza("measurement.redaction.client_ephemeral_aiid_generation", bool2, bool2, zzcc.zza$26);
        zzaq = zza("measurement.redaction.retain_major_os_version", bool2, bool2, zzcc.zza$27);
        zza("measurement.redaction.scion_payload_generator", bool2, bool2, zzcc.zza$28);
        zzas = zza("measurement.audience.dynamic_filters.oob_fix", bool2, bool2, zzcc.zza$29);
        zzat = zza("measurement.service.clear_global_params_on_uninstall", bool2, bool2, zzdg.zza);
        zzau = zza("measurement.sessionid.enable_client_session_id", bool2, bool2, zzdg.zza$1);
    }

    public static Map zzc(Context context) {
        zzhf zzhfVarZza = zzhf.zza(context.getContentResolver(), zzhq.zza(PZmDzEagKNdW.GaAcn), zzay.zza);
        if (zzhfVarZza == null) {
            return Collections.emptyMap();
        }
        return zzhfVarZza.zzc();
    }
}
