<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>RobloxPiano.AudioBenchmark</AssemblyName>
    <RootNamespace>RobloxPiano.AudioBenchmark</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/RobloxPiano.Audio/RobloxPiano.Audio.csproj" />
  </ItemGroup>
</Project>
