package com.google.android.gms.ads.internal;

import android.os.Build;
import com.facebook.AccessTokenCache;
import com.facebook.GraphRequest;
import com.google.android.gms.ads.internal.util.zzab;
import com.google.android.gms.ads.internal.util.zzay;
import com.google.android.gms.ads.internal.util.zzbt;
import com.google.android.gms.ads.internal.util.zzci;
import com.google.android.gms.ads.internal.util.zzs;
import com.google.android.gms.ads.internal.util.zzt;
import com.google.android.gms.ads.internal.util.zzx;
import com.google.android.gms.ads.internal.util.zzy;
import com.google.android.gms.common.util.DefaultClock;
import com.google.android.gms.internal.ads.zzazx;
import com.google.android.gms.internal.ads.zzbbk;
import com.google.android.gms.internal.ads.zzbbz;
import com.google.android.gms.internal.ads.zzbdk;
import com.google.android.gms.internal.ads.zzbed;
import com.google.android.gms.internal.ads.zzbon;
import com.google.android.gms.internal.ads.zzbpl;
import com.google.android.gms.internal.ads.zzbvx;
import com.google.android.gms.internal.ads.zzbyo;
import com.google.android.gms.internal.ads.zzbzs;
import com.google.android.gms.internal.ads.zzbzz;
import com.google.android.gms.internal.ads.zzcal;
import com.google.android.gms.internal.ads.zzcas;
import com.google.android.gms.internal.ads.zzcdg;
import com.google.android.gms.internal.ads.zzcft;
import com.google.android.gms.internal.ads.zzedb;
import okhttp3.internal.http1.HeadersReader;

/* JADX INFO: loaded from: classes.dex */
public final class zzv {
    public static final zzv zza = new zzv();
    public final zzbyo zzB;
    public final zzci zzC;
    public final zzcdg zzD;
    public final zzcas zzE;
    public final GraphRequest.Companion zzb;
    public final GraphRequest.Companion zzc;
    public final zzs zzd;
    public final zzcft zze;
    public final zzbzz zzf;
    public final zzt zzg;
    public final zzazx zzh;
    public final zzbzs zzi;
    public final zzab zzj;
    public final zzbbk zzk;
    public final DefaultClock zzl;
    public final HeadersReader zzm;
    public final zzbdk zzn;
    public final zzbed zzo;
    public final zzay zzp;
    public final zzbvx zzq;
    public final zzcal zzr;
    public final zzbon zzs;
    public final com.android.billingclient.api.zzo zzt;
    public final zzbt zzu;
    public final GraphRequest.Companion zzv;
    public final GraphRequest.Companion zzw;
    public final zzbpl zzx;
    public final AccessTokenCache zzy;
    public final zzedb zzz;

    public zzv() {
        GraphRequest.Companion companion = new GraphRequest.Companion(19);
        GraphRequest.Companion companion2 = new GraphRequest.Companion(22);
        zzs zzsVar = new zzs();
        zzcft zzcftVar = new zzcft();
        zzbzz zzbzzVar = new zzbzz();
        int i = Build.VERSION.SDK_INT;
        zzt zzyVar = i >= 30 ? new zzy() : i >= 28 ? new zzx() : i >= 26 ? new com.google.android.gms.ads.internal.util.zzv() : i >= 24 ? new com.google.android.gms.ads.internal.util.zzu() : new zzt();
        zzazx zzazxVar = new zzazx();
        zzbzs zzbzsVar = new zzbzs();
        zzab zzabVar = new zzab();
        zzabVar.zza = false;
        zzabVar.zzb = 1.0f;
        zzbbk zzbbkVar = new zzbbk();
        DefaultClock defaultClock = DefaultClock.zza;
        HeadersReader headersReader = new HeadersReader();
        headersReader.headerLimit = 0L;
        zzbdk zzbdkVar = new zzbdk();
        zzbed zzbedVar = new zzbed();
        zzay zzayVar = new zzay();
        zzbvx zzbvxVar = new zzbvx();
        zzcal zzcalVar = new zzcal();
        zzbon zzbonVar = new zzbon();
        com.android.billingclient.api.zzo zzoVar = new com.android.billingclient.api.zzo();
        zzoVar.zze = null;
        zzoVar.zzh = false;
        zzoVar.zza = null;
        zzoVar.zzf = null;
        zzoVar.zzb = null;
        zzbt zzbtVar = new zzbt();
        GraphRequest.Companion companion3 = new GraphRequest.Companion(20);
        GraphRequest.Companion companion4 = new GraphRequest.Companion(21);
        zzbpl zzbplVar = new zzbpl();
        AccessTokenCache accessTokenCache = new AccessTokenCache(19);
        zzedb zzedbVar = new zzedb();
        new zzbbz();
        zzbyo zzbyoVar = new zzbyo();
        zzci zzciVar = new zzci();
        zzcdg zzcdgVar = new zzcdg();
        zzcas zzcasVar = new zzcas();
        this.zzb = companion;
        this.zzc = companion2;
        this.zzd = zzsVar;
        this.zze = zzcftVar;
        this.zzf = zzbzzVar;
        this.zzg = zzyVar;
        this.zzh = zzazxVar;
        this.zzi = zzbzsVar;
        this.zzj = zzabVar;
        this.zzk = zzbbkVar;
        this.zzl = defaultClock;
        this.zzm = headersReader;
        this.zzn = zzbdkVar;
        this.zzo = zzbedVar;
        this.zzp = zzayVar;
        this.zzq = zzbvxVar;
        this.zzr = zzcalVar;
        this.zzs = zzbonVar;
        this.zzu = zzbtVar;
        this.zzt = zzoVar;
        this.zzv = companion3;
        this.zzw = companion4;
        this.zzx = zzbplVar;
        this.zzy = accessTokenCache;
        this.zzz = zzedbVar;
        this.zzB = zzbyoVar;
        this.zzC = zzciVar;
        this.zzD = zzcdgVar;
        this.zzE = zzcasVar;
    }
}
